---
title: "GreenData"
author: "Garrett B. Lucas"
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dictionary <- readr::read_csv(here::here("data", "green_dictionary.csv"))
green_data <- readr::read_csv(here::here("data", "green_data.csv"))
```

```{r}
print(green_data)
```

```{r}
green_data |>
  select(-id) |>
  unlist() |>
  unique()

green_data <- green_data |>
  mutate(
    across(
      -id,
      \(x) recode(x, "1" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "-99" = NA_real_)
    )
  )
```


```{r}
reversed <- dictionary |>
  filter(Keying = -1) |>
  pull(item)

green_data <- green_data |>
  mutate(
    across(
      all_of(reversed),
      \(x) recode(x, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1)
    )
  )
```

```{r}
green_data <- green_data |>
  rowwise() |>
  mutate(
    green_total = mean(c_across(green1:green5), na.rm = TRUE),
    comp_total = mean(c_across(comp1:comp10), na.rm = TRUE),
    intel_total = mean(c_across(intel1:intel10), na.rm = TRUE),
    open_total = mean(c_across(open1:open10), na.rm = TRUE),
    .after = id
  ) |>
  ungroup()
```

```{r}
green_data <- green_data |>
  mutate(
    across(
      green_total:open_total,
      \(x) 100* (x - 1) / (5 - 1),
      .names = "{.col}_pomp"
    )
  )
```

```{r}
ggplot(green_data) +
  aes(x = green_total_pomp) +
  geom_histogram()

green_data |>
  filter(!is.na(student))
         
ggplot(green_data) +
  aes(x = open_total_pomp, y = green_total_pomp, color = factor(student)) +
  geom_point() +
  geom_smooth(method = "lm")
```

